version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/nginx/certs:ro
      - ./www:/usr/share/nginx/html:ro

  trojan:
    image: trojangfw/trojan:latest
    container_name: trojan
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./trojan-config.json:/config.json:ro
      - /etc/letsencrypt/live:/etc/nginx/certs:ro
    environment:
      - TZ=Asia/Shanghai
