version: '3.8'

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/letsencrypt/live

networks:
  app_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/nginx/certs:ro
    depends_on:
      - trojan
    networks:
      - app_network

  trojan:
    image: trojangfw/trojan:latest
    container_name: trojan
    restart: unless-stopped
    volumes:
      - ./trojan-config.json:/config/config.json:ro
      - certs:/etc/certs:ro
    networks:
      - app_network
