version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  trojan:
    image: gists/trojan-go:latest
    container_name: trojan
    restart: unless-stopped
    ports:
      - "10443:10443"
    volumes:
      - ./trojan-config.json:/data/trojan.json:ro
      - ./certs:/etc/trojan/ssl:ro
    command: trojan-go -config /data/trojan.json
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
