version: '3.8'

volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/letsencrypt

networks:
  app_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - trojan
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  trojan:
    image: gists/trojan-go:latest
    container_name: trojan
    restart: unless-stopped
    ports:
      - "10443:10443"
    volumes:
      - ./trojan-config.json:/data/trojan.json:ro
      - letsencrypt:/etc/letsencrypt:ro
    command: trojan-go -config /data/trojan.json
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
