version: '3.8'

volumes:
  certs:
    # 定义公共的 volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/letsencrypt/live # 挂载系统目录

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/certs:ro # 挂载公共 volume
      - ./www:/usr/share/nginx/html:ro

  trojan:
    image: trojangfw/trojan:latest
    container_name: trojan
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./trojan-config.json:/config.json:ro
      - certs:/etc/certs:ro # 挂载公共 volume
    environment:
      - TZ=Asia/Shanghai
